---
ansible_become: True
ansible_user: root

physical_host: physical_host

container_networks:
  hostinterface:
    address: "1.3.3.7"
    netmask: "255.255.255.0"
    interface: eth1
    type: hostinterface

