---
ansible_become: True
ansible_user: root

physical_host: physical_host

container_networks:
  macvlan:
    address: "{{ ansible_host }}"
    netmask: "255.255.255.0"
    interface: eth0
    type: macvlan
